/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Club = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'memberCount' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const EventStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'pending' : IDL.Null,
  'past' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'status' : EventStatus,
  'title' : IDL.Text,
  'clubId' : IDL.Nat,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'registeredUsers' : IDL.Vec(IDL.Principal),
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'joinedClubs' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'email' : IDL.Text,
  'registeredEvents' : IDL.Vec(IDL.Nat),
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'read' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveEvent' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createClub' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createProfile' : IDL.Func([UserProfileInput], [], []),
  'deleteClub' : IDL.Func([IDL.Nat], [], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'getAllClubs' : IDL.Func([], [IDL.Vec(Club)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getClub' : IDL.Func([IDL.Nat], [IDL.Opt(Club)], ['query']),
  'getClubEvents' : IDL.Func([IDL.Nat], [IDL.Vec(Event)], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initAdmin' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinClub' : IDL.Func([IDL.Nat], [], []),
  'leaveClub' : IDL.Func([IDL.Nat], [], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'registerForEvent' : IDL.Func([IDL.Nat], [], []),
  'rejectEvent' : IDL.Func([IDL.Nat], [], []),
  'setAdminRole' : IDL.Func([IDL.Principal], [], []),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'unregisterFromEvent' : IDL.Func([IDL.Nat], [], []),
  'updateCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
  'updateClub' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateEvent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'updateProfile' : IDL.Func([UserProfileInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const Club = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'memberCount' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const EventStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'pending' : IDL.Null,
    'past' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'status' : EventStatus,
    'title' : IDL.Text,
    'clubId' : IDL.Nat,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'registeredUsers' : IDL.Vec(IDL.Principal),
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'joinedClubs' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'email' : IDL.Text,
    'registeredEvents' : IDL.Vec(IDL.Nat),
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'read' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveEvent' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createClub' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createProfile' : IDL.Func([UserProfileInput], [], []),
    'deleteClub' : IDL.Func([IDL.Nat], [], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'getAllClubs' : IDL.Func([], [IDL.Vec(Club)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getClub' : IDL.Func([IDL.Nat], [IDL.Opt(Club)], ['query']),
    'getClubEvents' : IDL.Func([IDL.Nat], [IDL.Vec(Event)], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initAdmin' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinClub' : IDL.Func([IDL.Nat], [], []),
    'leaveClub' : IDL.Func([IDL.Nat], [], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'registerForEvent' : IDL.Func([IDL.Nat], [], []),
    'rejectEvent' : IDL.Func([IDL.Nat], [], []),
    'setAdminRole' : IDL.Func([IDL.Principal], [], []),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'unregisterFromEvent' : IDL.Func([IDL.Nat], [], []),
    'updateCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
    'updateClub' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateEvent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'updateProfile' : IDL.Func([UserProfileInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };