/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Club {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'memberCount' : bigint,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Event {
  'id' : bigint,
  'status' : EventStatus,
  'title' : string,
  'clubId' : bigint,
  'date' : bigint,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'description' : string,
  'registeredUsers' : Array<Principal>,
  'location' : string,
}
export type EventStatus = { 'upcoming' : null } |
  { 'pending' : null } |
  { 'past' : null };
export interface Notification {
  'id' : bigint,
  'userId' : Principal,
  'read' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'principal' : Principal,
  'joinedClubs' : Array<bigint>,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'email' : string,
  'registeredEvents' : Array<bigint>,
}
export interface UserProfileInput {
  'bio' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveEvent' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createClub' : ActorMethod<[string, string, string, string], bigint>,
  'createEvent' : ActorMethod<[string, string, bigint, bigint, string], bigint>,
  'createProfile' : ActorMethod<[UserProfileInput], undefined>,
  'deleteClub' : ActorMethod<[bigint], undefined>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'getAllClubs' : ActorMethod<[], Array<Club>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllStudents' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getClub' : ActorMethod<[bigint], [] | [Club]>,
  'getClubEvents' : ActorMethod<[bigint], Array<Event>>,
  'getEvent' : ActorMethod<[bigint], [] | [Event]>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initAdmin' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinClub' : ActorMethod<[bigint], undefined>,
  'leaveClub' : ActorMethod<[bigint], undefined>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'registerForEvent' : ActorMethod<[bigint], undefined>,
  'rejectEvent' : ActorMethod<[bigint], undefined>,
  'setAdminRole' : ActorMethod<[Principal], undefined>,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
  'unregisterFromEvent' : ActorMethod<[bigint], undefined>,
  'updateCallerUserProfile' : ActorMethod<[UserProfileInput], undefined>,
  'updateClub' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateEvent' : ActorMethod<
    [bigint, string, string, bigint, string],
    undefined
  >,
  'updateProfile' : ActorMethod<[UserProfileInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];